name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # Step 3: Run backend tests
    - name: Run Tests
      run: |
        pytest tests/

    # Step 4: Setup Node.js and build frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install and Build Frontend
      working-directory: oil_price_dashboard/frontend
      run: |
        npm install
        npm run build

    # Step 5: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t myrepo/oil_price_dashboard:latest .

